title: Bearded QA
author: Bearded QA
email: your-email@domain.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  'no bullshit allowed'.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bearded.qa" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  beardedqa
instagram_username: bearded.qa
social:
  name: Tomasz Wojciechowski
  links:
    - https://www.linkedin.com/in/beardedqa/
    - https://github.com/beardedqa

disqus:
  shortname: beardedqa
# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
